module.exports = [
  'Dimension C-132',
  'Dimension C-137',
  'Earth',
  'Alphabetrium',
  'Arbolez Mentorosos',
  'Bird World',
  'Cronenberg World',
  'Dwarf Terrace-9',
  'Gazorpazorp',
  'Glapflap',
  'Hideout Planet',
  'On a Cob Planet',
  'Parblesnops',
  'Pawn Shop Planet', 
  'Planet Squanch',
  'Pluto',
  'Purge Planet',
  'Screaming Sun Earth',
  'Snorlab',
  'Interdimensional Customs',
];
